module.exports = {
    SubHeading: "We just need a few details so we can open your account.",
    Text1: "The information you provide will be held by Nationwide. We’ll use it to process your application and help manage your account(s) and any services you use. By continuing, you confirm you’ve had a chance to read how we use your information and are happy to start your application.",
    Text2: "Your country of birth",
    Text3: "Your nationality",
    Text4: "Do you have another nationality?",
    Link: "https://www.nationwide.co.uk/about/corporate-information/cookies-and-privacy/how-we-use-your-information",
    errorHead: "There are 3 errors on the page:",
    error1: "Please choose your country of birth.",
    error2: "Please choose your nationality.",
    error3: "Please choose your other nationality.",
    error4: "Your other nationality can’t be the same as your first nationality. Please choose another nationality, or change your choice above.",
    alertMessage1: "Error: Please choose your country of birth.",
    alertMessage2: "Error: Please choose your nationality.",
    alertMessage3: "Error: Please choose your other nationality.",
    alertMessage4: "Error: Your other nationality can’t be the same as your first nationality. Please choose another nationality, or change your choice above.",
    Text5: "Please check this information is correct so we can send your account details to you.",
    heading3: "Your contact details",
    title: "Title",
    firstName: "First Name",
    lastName: "Last Name",
    dob: "Date of birth",
    email: "Email address",
    mobileNo: "Mobile number",
    landlineNo: "Landline number",
    detailsFooterLine1: "Are your details incorrect?",
    detailsFooterLine2: "You can update them on our banking app or online.",
    detailsFooterLine3:"Find out how to update your details",
    Link2:"https://www.nationwide.co.uk",
    heading4:"Your address",
    subHeading4: "Address",
    Text6:"We’ll send your new account details to this address.",
    addressFooterLine1: "Is your address incorrect?",
    addressFooterLine2: "Call us on 08457 30 20 10 to update it. Please wait until your address has been updated before continuing with your application (this could take up to 3 days).",
}