module.exports = {
    checkYourDetailsStep: "Step 1 of 5",
    pageHeading: "Check your details",
    subHeading: "Please check this information is correct so we can send your account details to you.",
    checkYourDetailsParagraph: "The information you provide will be held by Nationwide. We’ll use it to process your application and help manage your account(s) and any services you use. By continuing, you confirm you’ve had a chance to read how we use your information and are happy to start your application.",
    link: "https://www.nationwide.co.uk/-/media/MainSite/documents/about/corporate-information/privacy-and-cookies/how-we-use-info/How-Nationwide-uses-your-information.pdf",
    linkContent: "how we use your information",
    yourContactDetailsHeading: "Your contact details",
    yourContactDetailsText: "Please check your contact details are correct so we can get in touch about your account change.",  
    title: "Title",
    firstName: "First name",
    lastName: "Last name",
    dob: "Date of birth",
    email: "Email address",
    mobileNo: "Mobile number",
    landlineNo: "Landline",
    yourAddressHeading:"Your address",
    yourAddressText:"We’ll send your new account details to this address. Please check it's correct.",
    addressTitle: "Address",
    radioButtonQuestion: "Are your details correct?",
    radioButtonYes: "Yes",
    radioButtonNo: "No",
    errorAlertHeading:"Error:",
    errorHeader: "There is 1 error on the page:",
    error: "Please choose an option.",
    errorLink: "https://nbs-banking-webapp-ipc-int.dev4.edb-a.eu-west-2.notprod.thenbs.io/check-your-details#areYourDetailsCorrectFieldLabel",  
}