module.exports = {
    pageHeading: "Your account change is complete, Alexandria.",
    pageSubHeading: "We’ve changed your current account to FlexDirect. It could take up to 48 hours for the change to show on your Digital Banking.",
    tableHeading: "Your account details will stay the same",
    sortCodeText: "Sort code",
    accountNumber: "Account number",
    arrangedOverdraft: "Arranged overdraft",
    finalPageWarningBeforeThreeMins: "To keep your details safe, they\’ll only be shown for",
    finalPageWarningAfterThreeMins: "We’ve hidden your account details to keep them safe.",
    nextStepHeading: "What\'s next?",
    stepOneText: "Your new card will arrive in the post in the next 7 – 10 working days, but you\’ll still be able to use your old card for up to 21 days after your account change.",
    stepTwoText: "Your PIN will stay the same (your PIN is a 4-digit code that allows you to use your card).",
    stepThreeText: "Any regular payments you had set up on your FlexAccount have been transferred to your FlexDirect.",
    stepFourText: "Take advantage of our FlexDirect interest free arranged overdraft offer and check your eligibility on Digital Banking.",
    stepFiveText: "If you haven\’t already, download our Banking app to manage your account on your mobile.",
    downlodBankAppLinkText: "Download our Banking app",
    downlodBankAppLink: "https://www.nationwide.co.uk/support/ways-to-bank/banking-app",
    noteHeading: "If you change your mind",
    phoneNumberText: "You\’ve got 28 days to cancel your account change. Just give us a call on 03457 30 20 11, and we’ll change your account back to the one you had before. We’re open Monday to Saturday, 8am to 6pm. Closed Sundays and Bank Holidays.",
    phoneNumberLinkText: "03457 30 20 11",
    phoneNumberLink: "tel:03457 30 20 11",
    faqHeading: "Got a question?",
    faqText: "Take a look at our frequently asked questions.",
    faqLinkText: "frequently asked questions",
    faqLink: "https://www.nationwide.co.uk/support"
};