module.exports = {
    backButton: 'Back to Your account',
    stepNumber: 'Step 4 of 5',
    pageHeader: 'Important information',
    pageParagraph1Text: 'Please read our important documents. We’ve emailed copies of these to nitin.banota@publicissapient.com so you can refer to them at any time.',
    pageParagraph2Text: 'If you’d like to understand more about the main fees and charges for this account, take a look at these documents.',
    pageLink1Text: 'Arranged Overdraft Agreement',
    pageLink2Text: 'Rates and Charges',
    pageLink3Text: 'Fee Information Document',
    pageParagraph3Text: 'Find full details of our Financial Services Compensation Scheme (FSCS) document below, which covers your accounts up to a total of £85,000. Also, our Charitable Assignment and Nationwide Rules, which apply to you as a member when you open this account.',
    pageLink4Text: 'FSCS document',
    pageLink5Text: 'Charitable Assignment',
    pageLink6Text: 'Nationwide Rules',
    pageHeading2: 'Read and agree to this important information',
    pageParagraph4Text: 'Please read our Pre-Contract Credit Information (PCCI) document and read and agree to our FlexDirect Terms and Conditions, and Declaration.',
    pageParagraph4TextWithoutOD: 'Please read and agree to our FlexDirect Terms and Conditions, and Declaration.',
    tncModalHeadingText: 'General Current Account agreement and Declaration',
    pcciModalHeadingText: 'Pre-Contract Credit Information',
    tncModalAgreementWords: 'By selecting ‘I agree’, I, Alexandria O\'Neil, confirm that I agree to the General Current Account agreement and Declaration, and understand that I will be entering into a legally binding agreement with Nationwide and I agree to be bound by its terms.',
    button1Text: 'PCCI document',
    button2Text: 'Terms and Conditions',
    pageWarningMessage: 'Note: By continuing, you confirm you’ve read this information and agree to be bound by the terms outlined in these documents.',
    tncHeaderLinkErrorText: 'You need to read and agree to the information in the Terms and Conditions document before continuing.',
    pcciHeaderLinkErrorText: 'You need to confirm you’ve read the information in the PCCI document before continuing.',
    tncAlertText: 'Error: You need to read and agree to the information in the Terms and Conditions document before continuing.',
    pcciAlertText: 'Error: You need to confirm you’ve read the information in the PCCI document before continuing.',
    overdraftModalHeader: 'Arranged Overdraft Agreement',
    overdraftAgreementWords: 'I, Alexandria O\'Neil, confirm that I have read the Arranged Overdraft Agreement document and understand that I will be entering into a legally binding agreement with Nationwide and I agree to be bound by its terms.',
    ratesAndChargesHyperlink: 'https://www.nationwide.co.uk/-/assets/nationwidecouk/documents/current-accounts/resources/p7430-rate-and-charges.pdf',
    nationwideRulesHyperlink: 'https://www.nationwide.co.uk/-/media/MainSite/documents/about/corporate-information/memorandum-and-rules.pdf',   
    feeInformationDocumentHyperlink: 'https://www.nationwide.co.uk/-/media/MainSite/documents/products/current-accounts/flexdirect/Fee-information-document-flexdirect.pdf',
    charitableAssignmentHyperlink: 'https://www.nationwide.co.uk/support/support-articles/legal-information/charitable-assignment',
    fscsDocumentHyperlink: 'https://www.nationwide.co.uk/~/media/MainSite/documents/shared/FSCS_Information_Sheet'
};