module.exports = {
Heading: "Something's gone wrong",
SubHeading: "We’re sorry, but there’s been a technical issue that wasn’t your fault.",
Text: "We’ve not been able to process your application at this time.",
iDErrorHeading: "We need to confirm your identity",
iDErrorText: "We just need to check your ID so that we can change your account. Find out what type of ID we need to see and how to provide your ID.",
iDErrorLink: "https://www.nationwide.co.uk/identity",
techErrorHeading: "Sorry, something's gone wrong",
techErrorText: "There was a technical issue, so we weren't able to process your application at this time. Please try again later.",
overdrawnErrorHeading: "Sorry, we can't change your account",
overdrawnErrorText: "As your account balance is in an unarranged overdraft, you'll need to pay this back before we can change your account. When your balance is within your arranged limit you can try again.",
jointAccountAppErrorHeading: "Sorry, we can’t change your account",
jointAccountAppErrorText: "We can’t currently support joint account changes on our Banking app. Please log in to Digital Banking on a laptop or computer to change your account.",
jointAccountBrowserErrorHeading: "Please continue to change your account",
jointAccountBrowserErrorText: "As your account is a joint account, you’ll need to apply using a different form.",
incorrectDetailsErrorHeading: "Please update your details",
incorrectDetailsErrorText: "We need to make sure we’ve got your details correct so that we can change your account. Find out how to update your details.",
incorrectDetailsErrorLink: "https://www.nationwide.co.uk/support/support-articles/how-to/update-details/change-your-address-or-phone-number",
noAccountFoundText: "We can’t change your account as you don’t have a FlexAccount. Please choose another account.",
noAccountsFoundErrorHeading: "Sorry, we can’t change your account",
landingPageErrorHeading: "You can’t access this page",
landingPageErrorText: "Sorry, you can’t access our account change application.",
emailBounceBackErrorHeading: "Sorry, something went wrong",
emailBounceBackErrorText: "We couldn’t send your documents to the email address you gave us. You’ll need to update your email address on Digital Banking before you can change your account.",
productChangeErrorHeading: "Sorry, something went wrong",
productChangeErrorText: "There's been a technical issue which means we couldn't change your account.",
genericErrorPageHeading: "Sorry, we can't change your account",
genericErrorPageText: "We can't change your account at this time. Please try again later."
}