module.exports = {
    stepText: "Step 3 of 5",
    backButtonLinkContent: "Back to Your account change",
    yourAccountHeading: "Your account",
    yourAccountSubHeading: "Choose your account preferences.",
    yourCardHeading: "Your card",
    yourCardSubHeading: "We’ll send you a new card in 7 to 10 working days, but you’ll still be able to use your old card for up to 21 days after your account change.",
    paperlessHeading: "Paperless communications",
    paperlessSubHeading: "As you’re applying for our online FlexDirect account, you agree to us sending your communications to the most up-to-date email address you give us, in the Internet Bank or any Nationwide app you sign up for. These include electronic documents, notices and other communications (in a PDF or text format).",
    yourCheckbookHeading: "Your chequebook",
    yourCheckbookSubHeading: "As part of our paperless initiative, we won’t send you a chequebook unless you ask us to.",
    checkBoxText: "I would like a chequebook",
    marketingPrefHeading: "Your marketing preferences",
    marketingPrefSubHeading: "We’d love to stay in touch to make sure you’re always getting the most from your membership with us. If you choose to receive marketing we’ll:",
    marketingPrefFirstList: "Make sure you’re one of the first to know about member-exclusive products, rewards and rates you could qualify for.",
    marketingPrefSecondList: "Share expert tips and tools, tailored for you, that could help you stay in control of your finances.",
    marketingPrefThirdList: "Give you opportunities to help shape our future products and services.",
    marketingPrefFooter: "It’s your choice to hear from us, you can change your marketing preferences at any time, and we promise to keep your data safe and never share it with anyone else for marketing purposes.",
    information: "Information:",
    informationMessage: "Whatever you choose, we’ll still keep you up to date with important service information, like your account statements.",
    heading3: "Tell us how you'd like us to contact you:",
    emails: "Emails",
    letters: "Letters",
    calls: "Calls",
    noEmailMarketingPrefSelectedError: "Please tell us if you’d like to receive marketing by email.",
    noLetterMarketingPrefSelectedError: "Please tell us if you’d like to receive marketing by post.",
    noCallsMarketingPrefSelectedError: "Please tell us if you’d like to receive marketing by telephone.",
    headerError3:"There are 3 errors on the page:",
    headerError2: "There are 2 errors on the page:",
    headerError1: "There is 1 error on the page:"
};