module.exports = {
    heading: "Your tax",
    subHeading: "Tell us if you have to pay tax outside the UK.",
    question1: "Are you liable to pay tax in any other country?",
    question1desc: "You may be liable to pay tax in another country if you’re a resident there or if you’re a citizen of the United States of America.",
    question2: "Are you a citizen of the United States of America?",
    question3: "Are you a resident for tax purposes in any country other than the United Kingdom?",
    country1Heading: "Country One",
    countryText: "Select which country you pay tax in",
    countryTINText: "Enter your Tax Identification Number (TIN) if you’ve been issued with one",
    country2Heading: "Country Two",
    country3Heading: "Country Three",
    oneErrorMessageHeader: "There is 1 error on the page:",
    twoErrorMessageHeader: "There are 2 errors on the page:",
    threeErrorMessageHeader: "There are 3 errors on the page:",
    question3ErrorHeaderLink: "https://nbs-banking-webapp-ipc-int.dev4.edb-a.eu-west-2.notprod.thenbs.io/your-tax#areYouTaxPayerOfOtherCountryFieldLabel",
    additionalUSCountryError: "You’ve already told us you’re a US citizen. Please choose a different country from the list. Or, change your answer for US citizenship to ‘no’.",
    otherCountriesAreTheSameError: "Error: You can’t choose the same country more than once. Please choose another country from the list or change your choice above.",
    otherCountriesAreTheSameErrorHeader: "You can’t choose the same country more than once. Please choose another country from the list or change your choice above.",
    countryTextError: "Please select which country you pay tax in.",
    taxResidentError: "You told us you’re liable to pay tax in another country. Please check the information you’ve provided is correct.",
    unselectedTaxLiableError: "Please tell us if you're liable to pay tax in another country.",
    unselectedUSCitizenError: "Please tell us if you’re a United States (US) citizen.",
    unselectedTaxResidentError: "Please tell us if you're a resident for tax purposes in any other country other than the United Kingdom.",
    invalidTINError: "Please enter your TIN correctly using letters, numbers and hyphens, where applicable.",
    tinTextTooLongError: "Please enter your TIN correctly - it needs to be between 1 and 20 characters.",
    question1ErrorHeaderLink: "https://nbs-banking-webapp-ipc-int.dev4.edb-a.eu-west-2.notprod.thenbs.io/your-tax#areYouTaxLiableFieldLabel",
    noResultsFound: "No results found\nPlease check the spelling and try again."
}