module.exports = {
    stepText: "Step 2 of 5",
    backButtonLinkContent: "Back to Check your details",
    accountCompareHeading: "Your account change",
    accountCompareSubHeading: "Check the details of your account change.",
    informationPanelHeading: "Information: Your account number, sort code and overdraft limit will stay the same.",
    existingAccountHeading: "Your existing FlexAccount details",
    firstTitle: "Monthly cost to maintain the account",
    secondTitle: "Manage your account",
    existingAccountSecondValue: "On our banking app or online, in branch and over the phone.",
    thirdTitle: "Account benefits",
    existingAccountMessage: "Note: When you change to FlexDirect any promotions you had with this account will stop immediately.",
    newAccountHeading: "Your FlexDirect details",
    newAccountSecondValue: "On our banking app or online.",
    existingAccountBenefits: "Important: As you've had a FlexDirect account before, you won't receive the 12-month credit interest offer or the interest free overdraft offer again.",
    accountBenefitOverdraftLessThanZero: "2% credit interest on credit balances up to £1500 for 12 months (if you credit £1000 each month). No interest charged on arranged overdrafts for 12 months. Eligibility criteria apply to both offers. You can apply for an overdraft once your account change is complete.",
    accountBenefitOverdraftGreaterThanZero: "2% credit interest on credit balances up to £1500 for 12 months (if you credit £1000 each month). No interest charged on arranged overdrafts for 12 months. Eligibility criteria apply to both offers.",
    importantMessage: "Important: If you’ve had a FlexDirect account before, you won’t receive the 12-month credit interest offer or the interest free overdraft offer again.",
    accountCompareFooterText: "If you cancel your account change within 28 days, we'll reinstate any offers that came with your FlexAccount."
};