module.exports = {
  // ID Gen Responses
  Response_idgen_appid: "appId",
  Response_idgen_channel: "channel",
  Response_idgen_productid: "productId",
  Response_idgen_newproductid: "newProductId",
  Response_idgen_accountnumber: "accountNo",

  // Error Response
  Response_error_code: "status.code",
  Response_error_type: "status.type",
  Response_error_retry: "status.retry",
  Response_error_message: "status.message",

  //Success Response
  Response_code: "status.code",
  Response_type: "status.type",
  Response_retry: "status.retry",
  Response_message: "status.message",

  // Error response Arrays
  Response_error_errors: "status.errors[0]",

  //Common for Account Manager end points
  Response_accountManager_accountid: "responsePayload.accountId",

  //Retrieve Account Details
  Response_accountDetail_investorTypeCode: "responsePayload.investorTypeCode",
  Response_accountDetail_creditScore: "responsePayload.creditScore",
  Response_accountDetail_availableBalanceAmt: "responsePayload.balanceInformation.availableBalanceAmt.currencyAmount.amount",
  Response_accountDetail_overdraftAmount: "responsePayload.overdraftInformation.agreedAmount.currencyAmount.amount",
    Response_accountDetail_accountInCollectionsIndicator: "responsePayload.accountInCollectionsIndicator",

  //Get Account Lock Response
  Response_accountLock_Code: "responsePayload.locks[0].code",
  Response_accountLock_Description: "responsePayload.locks[0].description",
  Response_accountLock_Code2: "responsePayload.locks[1].code",
  Response_accountLock_Description2: "responsePayload.locks[1].description",
  Response_accountLock_Code3: "responsePayload.locks[2].code",
  Response_accountLock_Description3: "responsePayload.locks[2].description",

  //Get Account List Response
  Response_accountList_ProductName: "responsePayload.accounts[0].productName",
  Response_accountList_SortCode: "responsePayload.accounts[0].sortCode",
  Response_accountList_AccountNumber: "responsePayload.accounts[0].accountNumber",

  //Check Eligibility Response
  Response_eligibility_promotionDesc: "responsePayload.promotionDescription",
  Response_eligibility_eStatementCode: "responsePayload.eStatementSelectionCode",
  Response_eligibility_checkBookCode: "responsePayload.chequeBookSelectionCode",
  Response_eligibility_isEligible: "responsePayload.isEligibleForAccount",
  Response_eligibility_errorCode: "responsePayload.eligibilityErrors[0].errorCode",
  Response_eligibility_errorMessage: "responsePayload.eligibilityErrors[0].errorMessage",
  Response_eligibility_eligibilityError: "responsePayload.eligibilityErrors",

  //IPC Service - Create Application Response
  Response_createApplication_appId: "",
  Response_createApplication_applicantRevision: "",
  Response_createApplication_applicationRevision: "",
  Response_createApplication_applicantId: "",
  Response_createApplication_CustomerNo: "",

  //IPC Service - Get Customer Details Response
  Response_getCustomerDetails_houseNameOrNumber: "responsePayload.personal.addresses.address.houseNameOrNumber",
  Response_getCustomerDetails_buildingName: "responsePayload.personal.addresses.address.buildingName",
  Response_getCustomerDetails_area: "responsePayload.personal.addresses.address.area",
  Response_getCustomerDetails_addressLineOne: "responsePayload.personal.addresses.address.addressLineOne",
  Response_getCustomerDetails_addressLineTwo: "responsePayload.personal.addresses.address.addressLineTwo",
  Response_getCustomerDetails_addressLineThree: "responsePayload.personal.addresses.address.addressLineThree",
  Response_getCustomerDetails_townOrCity: "responsePayload.personal.addresses.address.townOrCity",
  Response_getCustomerDetails_serviceNoRankAndName: "responsePayload.personal.addresses.address.serviceNoRankAndName",
  Response_getCustomerDetails_unitRegiment: "responsePayload.personal.addresses.address.unitRegiment",
  Response_getCustomerDetails_operationName: "responsePayload.personal.addresses.address.operationName",
  Response_getCustomerDetails_bfpoNumber: "responsePayload.personal.addresses.address.bfpoNumber",
  Response_getCustomerDetails_isBfpoAddress: "responsePayload.personal.addresses.address.isBfpoAddress",
  Response_getCustomerDetails_postcode: "responsePayload.personal.addresses.address.postcode",
  Response_getCustomerDetails_country: "responsePayload.personal.addresses.address.country",

  //AppStore Service - Get Application Response
  RAS_application_appId: "responsePayload.appId",
  RAS_application_journeyId: "responsePayload.journeyId",
  RAS_application_isJoint: "responsePayload.isJointApp",
  RAS_application_lastUpdatedOn: "responsePayload.lastUpdatedOn",
  RAS_application_createdOn: "responsePayload.createdOn",
  RAS_application_journeyType: "responsePayload.journeyType",
  RAS_application_applicantId: "responsePayload.applicants[0].id",
  RAS_application_applicantType: "responsePayload.applicants[0].applicantType",
  RAS_application_eligibility_errorCode: "responsePayload.errors[0].errorCode",
  RAS_application_eligibility_errorMessage: "responsePayload.errors[0].errorMessage",
  RAS_application_applicant_isCardReaderIssued: "responsePayload.applicants[0].isCardReaderIssued",
  RAS_application_applicant_matchStatus: "responsePayload.applicants[0].matchStatus",
  RAS_application_applicant_identityCheckMode: "responsePayload.applicants[0].identityCheckMode",
  RAS_application_applicant_impersonationCheckMode: "responsePayload.applicants[0].impersonationCheckMode",
  RAS_application_applicant_provisionalCisNo: "responsePayload.applicants[0].cisInfo.provisionalCisCustomerNumber",
  RAS_application_applicant_cisNo: "responsePayload.applicants[0].cisInfo.cisCustomerNumber",
  RAS_application_applicant_cisNo_isverified: "responsePayload.applicants[0].cisInfo.isCisCustomerNumVerified",
  RAS_application_applicant_CustomerIdStatus: "responsePayload.applicants[0].cisInfo.CustomerIdStatus",
  RAS_application_applicant_creationDate: "responsePayload.applicants[0].cisInfo.customerCreationDate",
  RAS_application_applicant_preferences_cardType: "responsePayload.applicants[0].preferences.cardType",
  RAS_application_applicant_preferences_isChequebookRequired: "responsePayload.applicants[0].preferences.isChequebookRequired",
  RAS_application_applicant_ExistingTaxDeclarationStatus: "responsePayload.applicants[0].existingTaxDeclarationStatus",
  RAS_application_channelInfo_originatingChannel: "responsePayload.channelInfo.originatingChannel",
  RAS_application_channelInfo_sourceSystemId: "responsePayload.channelInfo.sourceSystemId",
  RAS_application_channelInfo_businessTxCommChannel: "responsePayload.channelInfo.businessTxCommChannel",
  RAS_application_channelInfo_functionalUnit: "responsePayload.channelInfo.functionalUnit",
  RAS_application_channelInfo_distributionChannelTypeCode: "responsePayload.channelInfo.distributionChannelTypeCode",
  RAS_application_statusCode: "responsePayload.statusCode",
  RAS_application_statusReason: "responsePayload.statusReason",
  RAS_application_errors: "responsePayload.errors[0]",
  RAS_application_errorCode: "responsePayload.errors[0].errorCode",
  RAS_application_errorMessage: "responsePayload.errors[0].errorMessage",
  RAS_application_errorCode2: "responsePayload.errors[1].errorCode",
  RAS_application_errorMessage2: "responsePayload.errors[1].errorMessage",
  RAS_application_applicationState_state1: "responsePayload.applicationState[0].state",
  RAS_application_applicationState_state2: "responsePayload.applicationState[1].state",
  RAS_application_applicationState_state3: "responsePayload.applicationState[2].state",
  RAS_application_isOwnerTraceable: "responsePayload.isOwnerTraceable",
  RAS_application_isEligibleForAccount: "responsePayload.isEligibleForAccount",
  RAS_application_existingProducts_productId: "responsePayload.applicants[0].existingProducts[0].productId",
  RAS_application_existingProducts: "responsePayload.applicants[0].existingProducts[]",
  RAS_application_existingAccount_SortCode: "responsePayload.applicants[0].existingProducts[0].existingAccount.sortCode",
  RAS_application_existingAccount_Number: "responsePayload.applicants[0].existingProducts[0].existingAccount.number",
  RAS_application_existingProducts_agreedOverdraftLimit: "responsePayload.applicants[0].existingProducts[0].agreedOverdraftLimit",
  RAS_application_existingProducts_isInternalProductChangeCandidate: "responsePayload.applicants[0].existingProducts[0].isInternalProductChangeCandidate",
  RAS_application_existingProducts_isJointAccount: "responsePayload.applicants[0].existingProducts[0].isJointAccount",
  RAS_application_existingProducts_currentBalance: "responsePayload.applicants[0].existingProducts[0].currentBalance",
  RAS_application_existingProducts_availableBalance: "responsePayload.applicants[0].existingProducts[0].availableBalance",
  RAS_application_commsEvents: "responsePayload.applicants[0].commsEvents[]",
  RAS_application_commsEvents_destination: "responsePayload.applicants[0].commsEvents[0].destination",
  RAS_application_commsEvents_templateId: "responsePayload.applicants[0].commsEvents[0].templateId",
  RAS_application_commsEvents_timestamp: "responsePayload.applicants[0].commsEvents[0].timestamp",
  RAS_application_commsEvents_type: "responsePayload.applicants[0].commsEvents[0].type",
  RAS_application_commsEvents_deliveryStatus: "responsePayload.applicants[0].commsEvents[0].deliveryStatus",
  RAS_application_commsEvents_deliveryId: "responsePayload.applicants[0].commsEvents[0].deliveryId",
  RAS_application_commsEvents_deliveryTimestamp: "responsePayload.applicants[0].commsEvents[0].deliveryTimestamp",
  RAS_application_existingProducts_lockType: "responsePayload.applicants[0].existingProducts[0].existingAccount.accountLocks[0].lockType",
  RAS_application_existingProducts_lockId: "responsePayload.applicants[0].existingProducts[0].existingAccount.accountLocks[0].lockId",
  RAS_application_createdAt: "responsePayload.createdAt",
  RAS_application_offeredProducts_isInternalProductSwitch: "responsePayload.offeredProducts[0].isInternalProductSwitch",
  RAS_application_offeredProducts_effectiveAnnualInterestRate: "responsePayload.offeredProducts[0].effectiveAnnualInterestRate",
  RAS_application_offeredProducts_accountFee: "responsePayload.offeredProducts[0].accountFee",
  RAS_application_offeredProducts_accountFeeFrequency: "responsePayload.offeredProducts[0].accountFeeFrequency",
  RAS_application_offeredProducts_availableAccountFacility: "responsePayload.offeredProducts[0].availableAccountFacility",
  RAS_application_offeredProducts_promotions: "responsePayload.offeredProducts[0].promotions[0]",
  RAS_application_offeredProducts_promotions_id: "responsePayload.offeredProducts[0].promotions[0].id",
  RAS_application_offeredProducts_promotions_name: "responsePayload.offeredProducts[0].promotions[0].name",
  RAS_application_offeredProducts_promotions_isDenied: "responsePayload.offeredProducts[0].promotions[0].isDenied",
  RAS_application_offeredProducts_productId: "responsePayload.offeredProducts[0].productId",
  RAS_application_signedTerms1_signedOn: "responsePayload.applicants[0].signedTerms[0].signedOn",
  RAS_application_signedTerms1_version: "responsePayload.applicants[0].signedTerms[0].version",
  RAS_application_signedTerms1_documentType: "responsePayload.applicants[0].signedTerms[0].documentType",
  RAS_application_signedTerms2_version: "responsePayload.applicants[0].signedTerms[1].version",
  RAS_application_signedTerms2_documentType: "responsePayload.applicants[0].signedTerms[1].documentType",
  RAS_application_signedTerms3_version: "responsePayload.applicants[0].signedTerms[2].version",
  RAS_application_signedTerms3_documentType: "responsePayload.applicants[0].signedTerms[2].documentType",
  RAS_application_signedTerms4_version: "responsePayload.applicants[0].signedTerms[3].version",
  RAS_application_signedTerms4_documentType: "responsePayload.applicants[0].signedTerms[3].documentType",
  RAS_application_signedTerms5_version: "responsePayload.applicants[0].signedTerms[4].version",
  RAS_application_signedTerms5_documentType: "responsePayload.applicants[0].signedTerms[4].documentType",

  //AppStore Service - Get Applicant Response
  RAS_applicant_applicantId: "responsePayload.id",
  RAS_applicant_isActive: "responsePayload.isActive",
  RAS_applicant_isDeceased: "responsePayload.isDeceased",
  RAS_applicant_revision: "responsePayload.revision",
  RAS_applicant_createdAt: "responsePayload.createdAt",

  //IPC Service - Get Application status Response
  Response_getApplicationStatus_statusCode: "responsePayload.statusCode",
  Response_getApplicationStatus_existingTaxDeclarationStatus: "responsePayload.applicants[0].existingTaxDeclarationStatus",
  Response_getApplicationStatus_promotionDenied: "responsePayload.offeredProducts[0].promotions[0].isDenied",
  Response_getApplicationStatus_agreedOverdraftLimit: "responsePayload.existingProducts[0].agreedOverdraftLimit",
  Response_getApplicationStatus_sourceAccountFee: "responsePayload.existingProducts[0].accountFee",
  Response_getApplicationStatus_targetAccountFee: "responsePayload.offeredProducts[0].accountFee",
  Response_getApplicationStatus_isEligibleForAccount: "responsePayload.isEligibleForAccount",
  Response_getApplicationStatus_sortCode: "responsePayload.existingProducts[0].existingAccount.sortCode",
  Response_getApplicationStatus_accountNumber: "responsePayload.existingProducts[0].existingAccount.number",
  Response_getApplicationStatus_originalSubscriptionAmt: "responsePayload.originalSubscriptionAmt",
  Response_getApplicationStatus_targetSubscriptionAmt: "responsePayload.targetSubscriptionAmt",
  Response_getApplicationStatus_errorCode: "responsePayload.errors[0].errorCode",
  Response_getApplicationStatus_errors: "responsePayload.errors[0]",
  Response_getApplicationStatus_errorMessage: "responsePayload.errors[0].errorMessage",
  Response_getApplicationStatus_errorCode2: "responsePayload.errors[1].errorCode",                                                                    
  Response_getApplicationStatus_errorMessage2:  "responsePayload.errors[1].errorMessage", 
  Response_getApplicationStatus_errorCode3: "responsePayload.errors[2].errorCode",                                                                    
  Response_getApplicationStatus_errorMessage3:  "responsePayload.errors[2].errorMessage",   
  Response_getApplicationStatus_serviceStatusCode: "status.code",
  Response_getApplicationStatus_statusRetry: "status.retry",
  Response_getApplicationStatus_statusType: "status.type",
  Response_getApplicationStatus_statusMessage: "status.message",
  Response_getApplicationStatus_cardType: "responsePayload.applicants[0].preferences.cardType",

  //IPC Service - Update FATCA details
  Response_updateFatcaDetails_serviceStatusCode: "status.code",
  Response_updateFatcaDetails_statusRetry: "status.retry",
  Response_updateFatcaDetails_statusType: "status.type",
  Response_updateFatcaDetails_statusMessage: "status.message",
  Response_updateFatcaDetails_applicantRevision: "responsePayload.applicantRevision",


  RAS_applicant_isDeceased: "responsePayload.isDeceased",
  RAS_applicant_title: "responsePayload.personalInformation.name.title",
  RAS_applicant_titleText: "responsePayload.personalInformation.name.titleText",
  RAS_applicant_firstName: "responsePayload.personalInformation.name.firstName",
  RAS_applicant_lastName: "responsePayload.personalInformation.name.lastName",
  RAS_applicant_middleNames: "responsePayload.personalInformation.name.middleNames",
  RAS_applicant_address_buildingName: "responsePayload.addresses[0].buildingName",
  RAS_applicant_address_serviceNoRankAndName: "responsePayload.addresses[0].serviceNoRankAndName",
  RAS_applicant_address_operationName: "responsePayload.addresses[0].operationName",
  RAS_applicant_address_unitRegiment: "responsePayload.addresses[0].unitRegiment",
  RAS_applicant_address_bfpoNumber: "responsePayload.addresses[0].bfpoNumber",
  RAS_applicant_address_addressLineOne: "responsePayload.addresses[0].addressLineOne",
  RAS_applicant_address_addressLineTwo: "responsePayload.addresses[0].addressLineTwo",
  RAS_applicant_address_houseNameOrNumber: "responsePayload.addresses[0].houseNameOrNumber",
  RAS_applicant_address_townOrCity: "responsePayload.addresses[0].townOrCity",
  RAS_applicant_address_postcode: "responsePayload.addresses[0].postcode",
  RAS_applicant_address_area: "responsePayload.addresses[0].area",
  RAS_applicant_address_country: "responsePayload.addresses[0].country",
  RAS_applicant_address_isPrimaryAddress: "responsePayload.addresses[0].isPrimaryAddress",
  RAS_applicant_address_addressLocationId: "responsePayload.addresses[0].addressLocationId",
  RAS_applicant_address_addressType: "responsePayload.addresses[0].addressType",
  RAS_applicant_address_isBfpoAddress: "responsePayload.addresses[0].isBfpoAddress",
  RAS_applicant_marketingPref_isEmailPreferred: "responsePayload.marketingPreferences.isEmailPreferred",
  RAS_applicant_marketingPref_isPhonePreferred: "responsePayload.marketingPreferences.isPhonePreferred",
  RAS_applicant_marketingPref_isMailPreferred: "responsePayload.marketingPreferences.isMailPreferred",
  RAS_applicant_marketingPref_UpdateMarketingPreferencesOnCIS: "responsePayload.marketingPreferences.updateMarketingPreferencesOnCIS",
  RAS_applicant_contactInformation_landlineNumber: "responsePayload.contactInformation.landlineNumber",
  RAS_applicant_contactInformation_mobileNumber: "responsePayload.contactInformation.mobileNumber",
  RAS_applicant_contactInformation_email: "responsePayload.contactInformation.emailAddress",

  RAS_nationalityAndTax_applicantId: "responsePayload.id",
  RAS_nationalityAndTax_isLiableToPayTaxInAnotherCountry: "responsePayload.nationalityAndTax.isLiableToPayTaxInAnotherCountry",
  RAS_nationalityAndTax_isNonUkResidentForTaxPurposes: "responsePayload.nationalityAndTax.isNonUkResidentForTaxPurposes",
  RAS_nationalityAndTax_isUkResident: "responsePayload.nationalityAndTax.isUkResident",
  RAS_nationalityAndTax_isUsCitizen: "responsePayload.nationalityAndTax.isUsCitizen",
  RAS_nationalityAndTax_tinNumber1: "responsePayload.nationalityAndTax.taxPaidInCountries[0].tinNumber",
  RAS_nationalityAndTax_country1: "responsePayload.nationalityAndTax.taxPaidInCountries[0].country",
  RAS_nationalityAndTax_tinNumber2: "responsePayload.nationalityAndTax.taxPaidInCountries[1].tinNumber",
  RAS_nationalityAndTax_country2: "responsePayload.nationalityAndTax.taxPaidInCountries[1].country",
  RAS_nationalityAndTax_tinNumber3: "responsePayload.nationalityAndTax.taxPaidInCountries[2].tinNumber",
  RAS_nationalityAndTax_country3: "responsePayload.nationalityAndTax.taxPaidInCountries[2].country",
  RAS_nationalityAndTax_isDualNational: "responsePayload.nationalityAndTax.isDualNational"

};